globe-and-citizen/Celebrity-Fanalyzer

- src/components/PromptCard.vue
- src/pages/AdminPage.vue
- src/stores/prompts.js
- src/utils/date.js
Fix #35 
Now, when saving our prompts, the generated document has its id in the `year-month` format.
> Save `year-month` Format

- src/components/shared/ItemCard.vue
- src/components/shared/TheEntries.vue
- src/pages/SearchPage.vue
Changed ui layout for the search page and user entries section, to make it also a desktop version and more responsive.
> Changed UI layout for search page and user entries section

- src/components/Posts/TheComments.vue
- src/stores/stats.js
Implemented comments analysis using openAi api. 
Created an "Analyze sentimen" button. When clicked the request is sent to stats-api where we check if it exists in cache, if so return cached sentiment, otherwise we send an request to OpenAi to analyze users' sentiment based on comments and return + save in cache the result. 
Analyze button appears only if there are 10 or more comments! This way we reduce unnecessary calls to API. 
https://vimeo.com/961331486?share=copy
> Implemented ai comments analysis

- src/css/app.css
- src/layouts/MainMenu.vue
- src/pages/EntryPage.vue
- src/pages/PromptPage.vue
Refactored onSnapshot for user role update. Changed z-index for the menu bar that was overlapping on the map chart. And removed some unnecessary code/file. 
- From:
* Performance: Listens to all changes in the users collection, iterating over all document changes, which is inefficient.
* Network Usage: Higher network usage due to listening to all changes in the collection.
* Complexity: More complex logic due to the need to filter and check each change.
- To:
* Performance: Only listens to changes for the specific user's document, reducing unnecessary processing.
* Network Usage: Lower network usage as it only monitors a single document.
* Simplicity: Directly handles the specific user's data, making the logic simpler and more maintainable.
* Reliability: Immediate check for document …
> feat: refactoring onsnapshot for role update for better performance

- src/components/Admin/EntryCard.vue
- src/pages/CampaignPage.vue
- src/pages/EntryPage.vue
- src/pages/PromptPage.vue
- src/stores/advertises.js
- src/stores/clicks.js
- src/stores/impressions.js
- src/stores/likes.js
- src/stores/shares.js
- src/stores/stats.js
- Fixed new entry not showing when adding from prompt page. 
- Additionally fixed the "Update stats" function that was throwing an error for some reason. It might be related to some other changes that update prompt data. Moved iadd stats function to onBeforeRouteLeave to update stats for a prompt. 
- Additionally removed unused import and code that came across. 
- Changed the reset process for posts' interactions (likes, shares, etc). Instead of having reset function in each of the stores and calling them separately, I moved them all to stats store and implemented a function to reset all the interactions from all other stores. This way we reduce some line of code from our component and make it more readable. 
https://github.com/user-attachments/assets/95efae08-970e-4677-a00b-94f2c1a1dbee
> Fixed new entry not showing + additional changes, fixes

- src/stores/user.js
Fixed: If you search for a user in the Admin Panel’s USERS tab and they don’t have a role field defined in the database, they won’t be displayed.
> Fixed issue - Display of the missing role field.

- src/components/Admin/EntryCard.vue
Added additional visible indications for users to know the image is required. Also added additional tooltip messages showing what fields are required depending on what fields are filled.
> Visible indications for users to know the image is required #476

- src/components/Admin/EntryCard.vue
- src/components/Posts/TheAnthrogram.vue
In some cases, (after previous fix) for example for writers there are no available prompts showing in the menu when creating an entry. Fixed this by fetching all available prompts if there are none in the store loaded.
> Fix for not showing available prompt for entries in some cases

- src/stores/notifications.js
Fixed: Clicking on the subscribe button in Prompt's page is not changing the subscribe count instantly.
> Fixed: Clicking on the subscribe button in Prompt's page is not changing the subscribe count instantly.

- src/pages/IndexPage.vue
- src/utils/imageConvertor.js
The new width and height are calculated based on the aspect ratio, using the smaller of the width and height ratios if the image exceeds the maximum allowed dimensions.
This ensures that the aspect ratio is preserved, so no distortion occurs during resizing.
> fix:#541 Fix image resizing, so tall images are correctly handled

- src/components/shared/ArticleSkeleton.vue
- src/pages/SearchPage.vue
The amount of skeletons currently is set to 10 but could be set in the future based on the amount of the lazy loaded prompts that will be fetched.
> feat:#534 implemented loading skeleton cards to be a specific number and responsie to UI

- src/components/Admin/ManagePromptsEntries.vue
- src/components/Admin/TableEntry.vue
- src/css/app.css
Implemented clickable table columns each to corresponding endpoint. Clicking on author name should redirect to author profile page. Clicking on prompt or entry title should take you to that specific entry. 
Also I adjusted table UI so when expanding the prompt, entries columns would have the same width and match parent table.
Adjusted entries row color to easily see the differences between prompts and entries.
> 565 add clickable links for entry title and author name

- src/components/Admin/EntryCard.vue
- src/stores/entries.js
In order for writers to be able to withdraw money in case they are winners, there should be an escrowId for each entry. 
This fix will fetch from prompts, escrow id for each entry that doesn't have an escrowId. 
On creation phase of entry, escrowId will be populated with correct id.
> feat:#548 added escrow id for entries on writers admin panel

- src/components/Admin/ManagePromptsEntries.vue
- src/components/Admin/TableEntry.vue
- src/components/Posts/ShareComponent.vue
- Added the ability to directly share specific prompts and entries from the **Manage Prompts & Entries** table.
- Integrated the sharing functionality using `ShareComponent.vue`.
- Users can now easily share specific prompts and entries via the new share option in the table.
> FEAT/#570 Sharing the Entry or Prompt You Just Created

- src/components/Advertiser/AdvertiserTable.vue
- Fixed the inaccurate advertisement status for published ads. Once the advertisement has been published, the status shows as `Published`.
> fix:#616 - Inaccurate Advertise status for published advertise

- src/components/Admin/EntryCard.vue
- src/components/Admin/PromptCard.vue
Restricted entry creation for unfunded prompts (prompts that don't have an escrowId). 
Also fixed the issues with cached prompts in the prompts menu when creating entry (it required clearing cache to be able to see a new prompt, now it will fetch for new prompts each time the dropdown is opened)
> fix:#609 - fixing bug and check escrow id for entry

- src/components/shared/TheHeader.vue
- src/pages/PublicProfilePage.vue
Display a message :
Fixes #635 
I used The `defineExpose` function allows a controlled and clean way to make specific internal methods available to the parent or other components.
> feat:#635 - implemented display no entries message & button

- src/components/Admin/EntryCard.vue
- src/components/Admin/PromptCard.vue
Admins should not be allowed to create prompts or entries on behalf on other users, as there is no current use case for this feature. Prompts/entries should only be create on behalf of the current user.
Fixes #621 
I disabled the `Select Author` field, and this field is automatically set to the current user in the prompt and entry creation form.
--
> fix:#621 - fixed admin create entry prompt

- src/pages/PublicProfilePage.vue
When a user does not upload a profile picture, the profile picture field should display the initials of the user (e.g., "J" for John Doe) instead of remaining blank.
Fixes #642 
--
> feat:#642 - implement default initials profile pic

- src/components/Profile/ProfileTab.vue
The user profile page previously lacked a complete interface for managing profile pictures, including options to preview, save, cancel, and delete profile pictures.
- **Upload Dialog:** Added a modal dialog that opens when the user opts to upload a profile picture.
- **Image Preview:** Integrated a preview area within the dialog to allow users to view the uploaded image before saving.
- **Save and Cancel Buttons:** Enabled users to confirm or discard the upload with "Save" and "Cancel" buttons.
- **Delete Button:** Introduced a "Delete" button for users to remove their current profile picture.
- Refined the dialog layout to incorporate all four actions—Upload, Preview, Save, Cancel, and Delete—for a complete user experience.
- Improved button styling and positioning to maintain a …
> feat:#636 - implemented profile picture upload dialog

- functions/index.js
Previously, it was calculated as 1 MATIC for every 20 clicks, 1 MATIC for every 20 visits, and 1 MATIC for every 100 impressions on cloud functions. As a result, it was expiring too quickly.
Fixes #662
Now, it is calculated as 1 MATIC for every 1000 clicks, visits, or impressions.
> fix:#662 - Fixed advertisement status incorrectly show budget crossed

- src/components/Admin/ManagePromptsEntries.vue
- src/pages/SearchPage.vue
- test/cypress/e2e/admin-prompt-entry.cy.js
This PR addresses the issue where the "Load More" button appears incorrectly after filtering prompts by category and date on the search page. The bug caused an unnecessary "Load More" button to be displayed.
**Fixes Implemented**
- Adjusted the filtering logic to properly check the filtered results count and ensure that the "Load More" button only appears if additional prompts are available for loading.
- Introduced a state reset for the "Load More" button when both category and date filters are applied, preventing incorrect UI states.
Fixes #658 
--
> fix:#658 - Fix load more button after filtering

- src/pages/admin/AdminIndex.vue
This PR addresses the issue where both the Admin Panel and the newly selected tab remained active in the main menu when navigating to another tab.
**Fix Implemented:**
Ensured that the active state of the previously selected tab is removed when a new tab is clicked.
Updated the menu logic to maintain only the currently selected tab as active.
Fixes #660 
--
- Verified that switching between tabs updates the active state correctly.
- Tested edge cases, including rapid switching between tabs and navigating back to the Admin Panel.
> fix:#660 - Fixed main menu admin table remain active

- src/pages/SearchPage.vue
- src/stores/prompts.js
This PR resolves the issue where the "Load More" button was visible even after loading the last prompt or entry in the Search Page, Manage Prompt and Entry Table.
**Fix Details**
Added a condition to check if the last prompt or entry has been loaded.
Ensured the "Load More" button is hidden once all data is loaded.
Updated relevant components for consistent behavior across the Search Page, Manage Prompt Table, and Manage Entry Table.
Fixes #667 
--
- Verified the "Load More" button does not appear when the last prompt/entry is loaded.
- Ensured clicking the button (if visible) does not cause unexpected behavior.
- Tested on all affected pages to confirm consistent functionality.
> fix:#667 - Fixed load more button visible

- .github/workflows/cypress.yml
- src/components/Profile/SettingsTab.vue
- src/stores/user.js
This PR implements the ability for users to delete their own accounts directly from the Settings page.
**Changes**
- Added a "Delete Account" button to the Settings page UI.
- Clicking the button opens a confirmation dialog to prevent accidental deletions.
- Integrated a confirmation dialog requiring users to type "DELETE" to confirm account deletion, reducing accidental actions.
- Implemented account deletion from Firebase Authentication and associated Firestore data.
- Ensures the user is automatically logged out post-deletion.
- Added a success notification upon successful account deletion.
Fixes #684 
--
> feat:#684 - Delete account
