globe-and-citizen/Celebrity-Fanalyzer

src/components/ArticleSkeleton.vue
src/pages/SearchPage.vue

Creation of Article Skeleton component to be a skeleton model for article.

feat: Create skeleton model for article

---

.editorconfig
.eslintrc.js
index.html
src-pwa/custom-service-worker.js
src-pwa/register-service-worker.js

Just apply existing editor config and pretier rules in my IDE and run `npm run format`

feat: add editor config rules and format code using prettier

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- Edited the CONTRIBUTING.md to reflect using the three auto formaters we use.
- Added a CODE_OF_CONDUCT.md
- Edited the README.md to give a little more detail about what we are trying to accomplish
- Tried to make this commit conform to the _https://www.conventionalcommits.org/en/v1.0.0/_ standard

docs: Updating the Standard Trio of docs

---

src/pages/PromptPage.vue

Set bg collor to the q-page to fix the probleme

fix: fix image display on prompte entry

---

src/pages/IndexPage.vue

Intention to Close #51. 
I  decided instead of creating a whole new page, to use a modal instead. Reading the original content, I felt it was too centered on my personal story and no longer reflected a team approach. This allowed much of the content to be removed. Also, I wanted to limit the number of pages added so that simplicity of user Navigation could be maintained.
Quasar made this easy because it provided out-of-the-box-functionality for a modal and also for an accordion drop down menu. Between these two additions to the website, I thought that the addition of another dedicated page was unnecessary. 
--- …

Adding content re: the "Why" page.

---

src/pages/EntryPage.vue

Enable Anthrogram for entries
---
---

feat: enable antrhogram on entry

---

src/components/EntryCard.vue
src/components/PromptCard.vue

Add hyperlink to QEditor toolbar and remove formatting when paste text.
Fix #80 #81 
---
---

BugFix Production

---

src/pages/AdminPage.vue

Fix #92 
---
Due to this being a bug in production, I decided not to test the prompt/entry creation and deletion.
But there will be no problem considering that nothing relative has changed.
---

Reloads all content no matter it's on local storage

---

src/pages/EntryPage.vue

Very simple fix: I just needed to add margin to the bottom of the component.
INSERT YOUR DESCRIPTION HERE.
---
---
Second attempt to push this to do a pull request. This time though I pulled a clean version of the remote develop branch.
The actual fix couldn't be simpler, I just added q-mb-xl to `<section class="q-pa-md q-mb-xl" style="margin-top: 100%">`
I also added simple HTML comments to delineate the sections. Sometimes I find these useful but I leave it to your sense of style to keep or not to keep.

bugfix(EntryPage.vue): Ensure that Rxn Btns Show

---

src/components/TheComments.vue
src/pages/EntryPage.vue

INSERT YOUR DESCRIPTION HERE.
---
Added function for counting labels of replied comments. 
---
The review can be done after checking all items.

Comment to entries njavokhir

---

src/components/TheHeader.vue
src/pages/AdminPage.vue
src/pages/EntryPage.vue
src/pages/ProfilePage.vue
src/pages/SearchPage.vue
src/pages/YearArchivePage.vue

Created reusable component: `TheHeader.vue` and added back button to it.
Fix #91
---
---

Reusable Toolbar + Universal Back Button

---

src/pages/SearchPage.vue
src/pages/YearArchivePage.vue

Before requesting this pull request, I checked all of items and it is working. 
This pull request for #109 issue.

Advanced searching functionality

---

src/pages/IndexPage.vue

INSERT YOUR DESCRIPTION HERE.
---
---
This merge should affect ONLY the IndexPage.vue. It is only regarding content changes to that page. This merge closes #96.

fix Issue #96, Stravid87/fix index typos

---

src/components/Admin/ManageErrors.vue
src/components/Admin/ManageFeedbacks.vue
src/components/Profile/FeedbackTab.vue
src/components/Profile/ProfileTab.vue
src/components/Profile/SettingsTab.vue
src/pages/AdminPage.vue
src/pages/ProfilePage.vue
src/stores/feedbacks.js
src/stores/index.js

Creates a feedback system.
Closes #127 
---
---

Feedback System

---

src/components/Admin/EntryCard.vue
src/stores/entries.js

Bug fixed in production.
Fix #166

[BugFix] Edit/Delete Entry

---

src/components/TheComments.vue
src/components/__tests__/TheComments.spec.js
src/pages/EntryPage.vue
src/pages/PromptPage.vue
src/stores/comments.js
test/cypress/e2e/comment.cy.js

This PR brings the following changes:
- Refactors the `comment.js` file and makes it more generic to be used not only by entries but also by prompts;
- Adds comments tab to prompts;
- Keeps the test structure working according to the applied changes.
Closes #128

Comments on Prompts

---

src/pages/ProfilePage.vue

Added `max-file-size` of 1MB to avoid errors.
Fix #173

Added notification when restricting an image

---

src/components/TheComments.vue
test/cypress/e2e/comment.cy.js

Resolve #175 
I am using one file for testing comment of both entry and prompt.

improved entry and prompt cypress testing

---

src/components/Admin/EntryCard.vue
src/components/Admin/ManagePromptsEntries.vue
src/components/Admin/PromptCard.vue
src/components/Admin/ShowcaseCard.vue
src/components/Posts/ShowcaseArt.vue
src/pages/AdminPage.vue
src/pages/PromptPage.vue
src/stores/index.js
src/stores/prompts.js
src/stores/storage.js

Creates a tab on Prompt Card that handles with Showcase Art.
In Posts, displays the uploaded arts.
Close #129

Showcasing Art

---

src/pages/ProfilePage.vue
src/stores/storage.js

Bugfix / Upload Profile Picture

---

src/components/Admin/PromptCard.vue
src/components/Admin/ShowcaseCard.vue
src/components/Posts/ShowcaseArt.vue

Artist Carousel

---

src/stores/comments.js
test/cypress/e2e/comment.cy.js

Please, include:
- A description of the changes proposed in the pull request.
- A reference to a related issue in your repository:
- Add keyword "close", "fix" or "resolve" to inform the issue related.
Example: Resolve #160 
---
I removed unnecessary code on cypress testing and added one check for comments.js file into updating comment function.
---
The review can be done after checking all items.

Fixed timestamp error and changed something on commenting cypres test

---

test/cypress/e2e/comment.cy.js

There is a small bug on testing comment. I fixed it. In addition, after pulling from develop, I face conflicts and solved.

Fixing test error/javokhir

---

src/components/Admin/PromptCard.vue
src/stores/prompts.js

Deleting Relationships

---

.github/workflows/cypress.yml
.github/workflows/vitest.yml

ADD CODE COVE TO UNIT TEST
---
Before requesting a review of this Pull Request, I have certified that I have tested the following items in the application and all have passed my local tests without any side effects:
---

feat: add code cov to vitest

---

src/components/Posts/ThePost.vue

Moved to between title and content.

[Feature] Reposition author section

---

src/components/Admin/ManageErrors.vue
src/stores/errors.js

refactor error
---
Before requesting a review of this Pull Request, I have certified that I have tested the following items in the application and all have passed my local tests without any side effects:
---

refactor: refactor error store

---

src/components/Posts/ShowcaseArt.vue

---
When clicking screen to close dialog, full content don't scroll.
---

Dont scroll page/javokhir

---

src/pages/EntryPage.vue
src/pages/PromptPage.vue
src/pages/PublicProfilePage.vue
src/stores/__tests__/comments-async.spec.js
src/stores/__tests__/share.spec.js
test/cypress/e2e/entries.cy.js
test/cypress/e2e/public-profile.cy.js

404 on the prompt and entry page when have a slow network. Increase the timeout without slowing the page

Feature/fix 404 on the prompt and entry page when have a slow network. Increase the timeout without slowing the page

---

src/stores/__tests__/prompts.spec.js

Improved tests for editing and deleting the comments

Test: Edit and Delete Prompt

---

package-lock.json
package.json
src/stores/index.js

Secure localStorage data with high level of encryption and data compression.
- Secure data using  Base64 encoding;
- Compress data before storing it to localStorage;

Feature: Encrypt Local Storage

---

src/stores/entries.js
src/stores/prompts.js
src/stores/visitors.js

Now, when you delete a prompt/entry, the visitors collection is deleted as well.

Bugfix: Delete Entry

---

src/components/Admin/ManageFeedbacks.vue
src/components/Profile/FeedbackTab.vue
src/components/shared/TheHeader.vue
test/cypress/e2e/feedbacks.cy.js
test/cypress/e2e/search.cy.js

Test: Feedbacks

---

cypress.config.js
src/stores/__tests__/errors.spec.js
src/stores/__tests__/user.spec.js
vitest.config.js

build: setup retry for vitest and cypress

---

src/components/Admin/EntryCard.vue
src/components/Admin/ManagePromptsEntries.vue
src/components/Admin/PromptCard.vue
src/components/Admin/TableEntry.vue
src/pages/IndexPage.vue
src/pages/PromptPage.vue
src/pages/SearchPage.vue
src/stores/__tests__/entries.spec.js
src/stores/__tests__/prompts.spec.js
src/stores/__tests__/share.spec.js
src/stores/__tests__/user.spec.js
src/stores/notifications.js
src/stores/prompts.js

Fix Ci error by refactoring prompt default state

---

src/stores/__tests__/visitor.spec.js
src/stores/visitors.js

Created tests for visitors in Vitest

Test: Visitors

---

src/pages/EntryPage.vue
src/pages/PromptPage.vue
src/router/routes.js

fix: fix routing error

---

src/components/shared/ItemCard.vue

feat: link for items to improve accessibility

---

src/pages/EntryPage.vue
src/pages/StatsPage.vue
src/router/routes.js
src/stores/index.js
src/stores/stats.js
src/utils/activityTracker.js

I added specific statistics as suggested in the issue #324

Feature: Stats Collection

---

src/pages/EntryPage.vue

fix: fix entry mach

---

src/pages/StatsPage.vue
src/stores/stats.js

Now we are using JavaScript's native fetch to make statistics requests

feat: Javascript Fetch on Stats

---

src/pages/EntryPage.vue
src/pages/StatsPage.vue
src/stores/stats.js
src/utils/activityTracker.js

Using the API and database from https://stats-api.up.railway.app.

feat: Stats API integration

---

src/components/Admin/ManageReports.vue
src/components/Posts/Comments/DisplayComment.vue
src/components/__tests__/TheComments.spec.js.dep
src/stores/comments.js
src/stores/reports.js

- Removed console.logs
- Removed unuseful varables
- Ran formatter comman
- Interacted with deleted content for resolving #333

Reporting-comment/njavokhir

---

src/components/Posts/Graphs/LikesBar.vue

Fix:Display unpopulated dates in the Likes chart #313

---

src/components/Admin/TableEntry.vue
src/pages/PromptPage.vue
src/stores/comments.js
src/stores/likes.js
src/stores/shares.js

Hide Edit /Delete button if the role is writer and still be able to edit/delete the entries he wrote.

fix: hide edit/delete button

---

src/pages/admin/AdminIndex.vue
src/pages/admin/ErrorsIndex.vue
src/pages/admin/FeedbacksIndex.vue
src/pages/admin/PromptsIndex.vue
src/pages/admin/ReportsIndex.vue
src/pages/admin/UsersIndex.vue
src/pages/profile/FeedbackIndex.vue
src/pages/profile/ProfileIndex.vue
src/pages/profile/ProfileTab.vue
src/pages/profile/SettingsIndex.vue
src/pages/profile/SubscriptionsIndex.vue
src/router/admin.js
src/router/profile.js
src/router/routes.js
src/stores/entries.js
src/stores/prompts.js

Profile and Admin router updated, now user can directly access to the individual tab

Feat: Improves router navigation

---

src/components/Profile/LoginForm.vue
src/layouts/MainMenu.vue

##TASK
A pop-up window appears when the role changes for a user. After logout the email will populate in the login page.

Logout Modal open after role update and logout

---

src/stores/prompts.js

fixed the issue with not fetching months prompt, now we will always fetch the last prompt available

fixed the issue with not fetching months prompt

---

src/layouts/MainMenu.vue
src/stores/prompts.js

Added snapshot for real time implementation for role update

user role update issue resolved

---

src/components/Posts/TheComments.vue
src/components/shared/NotificationBubble.vue
src/pages/EntryPage.vue
src/stores/entries.js
src/stores/notifications.js

Grouped similar notifications

---

src/components/Posts/Graphs/HalfDonought.vue
src/components/Posts/Graphs/Map/LeafletMap.vue
src/components/Posts/Graphs/PopularityGauge.vue
src/components/Posts/TheAnthrogram.vue

- Fixed activity chart to position it without text overflows on mobile
- Fixed popularity gauge to be readable and all text to be visible on mobile + centered the chart in parent container on mobile
- Fixed map chart so touch won't be propogated to parent component and so the tab won't be changed when scrolling inside the map. Also made a map smaller on mobile so it would be easier to navigate.

fix: fixes for charts alignments and behaviour on mobile

---

src/components/Posts/Graphs/Map/handlingFunctions.js

Fixed the issues when there was 0 likes and 0 dislikes but 1 comment for a specific country, the country was still showing on the map, as there was an interactions. (Was showind with 0 values. 0 likes 0 dislikes, 1 commen).

fix: fixes empty interactions still showing on map issue

---

.github/workflows/cypress.yml
package.json

Feature/fix cypress ci PR for demo

---

src/components/Admin/EntryCard.vue
src/components/Admin/ManagePromptsEntries.vue
src/components/Admin/PromptCard.vue
src/components/Admin/TableEntry.vue
src/components/shared/TheEntries.vue
src/pages/PromptPage.vue
src/pages/admin/AdminIndex.vue
src/router/admin.js
src/stores/entries.js

update the way people write entries

update the way people write entries

---

src/components/Admin/WalletPaymentCard.vue
src/components/Advertiser/AdvertiseCard.vue
src/components/Advertiser/AdvertiserTable.vue
src/web3/transfers.js

i added try catch and logs to track the errors.. 
also add metamask common error handler , help for debug.

add logs for checks

---

.firebaserc
firebase.json
firestore.indexs.json
firestore.rules
src/pages/PromptPage.vue
src/stores/prompts.js

Month not found error fixed

---

src/stores/prompts.js

Fixed issue prompt not showing after creation

Fixed issue prompt not showing after creation

---

src/components/Advertiser/CampaignCard.vue
src/pages/SearchPage.vue

issue resolved for 423

---

src/stores/entries.js

Fixed the issue when removing the entry for a prompt and going back to the prompt.
https://github.com/user-attachments/assets/f1b8f9b4-5e7d-4030-901f-5d8f8bc104d6

fix/Deleted entry still shown on prompt page #458

---

src/components/Advertiser/AdvertiseCard.vue
src/components/Advertiser/AdvertiserTable.vue
src/components/Advertiser/CampaignCard.vue
src/components/Posts/ThePost.vue

Fixed: Formatting for Advertisement Blurbs.

Fixed: Formatting for Advertisement Blurbs

---

src/components/shared/TheEntries.vue

added login redirection for unauthenticated users while clicking to create entry button.

added login redirection for unauthenticated users while clicking to create entry button.

---

src/components/shared/TheHeader.vue

Minor changes on the Header Title and subtitle view.

Minor changes on the Header Title and subtitle view.

---

src/components/shared/LoadingSpinner.vue
src/layouts/MainLayout.vue
src/router/index.js
src/stores/index.js
src/stores/loading.js

Fixed: Progress / "Loading Wheel" to Display During Navigation

Fixed: Progress / "Loading Wheel" to Display During Navigation

---

src/components/Admin/ManagePromptsEntries.vue
src/components/Admin/TableEntry.vue
src/components/Advertiser/AdvertiserTable.vue
src/stores/entries.js

* Refactored "Created" column to show the Month/Day/Year
* Sorted entries to place the most recent at the top for both editors and for admins when expanding the prompt
* Made columns sortable for writers (created and title columns)
* Minor fixes (added await in async functions, fixed non existing fetchAdminsAndWriters() to use fetchAdminsAndEditors())

Organize entries by created #470

---

src/components/Admin/EntryCard.vue

Added a check to verify if current href is "month" to take the prompt from the month prompt store instance, otherwise check the all prompts list.

Fixed no prompt available for selection #474

---

src/components/Posts/TheComments.vue
src/components/shared/CommentsSkeleton.vue
src/stores/comments.js

Done: skeleton-comments-during-loading

enhancement:skeleton-comments-during-loading-482

---

src/pages/CampaignPage.vue
src/stores/advertises.js

enhancement:optimize-ad-fetching-on-campaign-page

enhancement:optimize-ad-fetching-on-campaign-page

---

src/components/Admin/PromptCard.vue

Added a check when submitting the prompt to check if the title already exists or if the title is "Month" than notify user to change the title.

Fix for prompts url edge cases

---

src/components/Admin/PromptCard.vue

Fixed: When Editing Your Own Prompt, You Need Another Title #506

Fixed: When Editing Your Own Prompt, You Need Another Title #506

---

src/components/Profile/LoginForm.vue

Added Regex for email Sign Up.

Enhancement: Email Sign Up Regex Check

---

src/components/Posts/ThePost.vue

Fixed: Like/Dislike button in advertisement is not working.

Fixed: Like/Dislike button in advertisement is not working. 

---

src/components/Posts/TheComments.vue

Fixed: Page is reloading everytime while writing the (second) comment.

Fixed: Page is reloading everytime while writing the (second) comment.

---

src/components/Advertiser/AdvertiserTable.vue

Fixed: Editable Advertisements #522. Now all the advertisement except the one which is expired can be edited.

Fixed: Editable Advertisements #522

---

src/components/Profile/LoginForm.vue

Improve UI for forgot password button

---

src/components/Admin/EntryCard.vue
src/components/Admin/PromptCard.vue
src/components/Advertiser/AdvertiseCard.vue

1.User interface improves
2.All card required field show in hint.
3.image name show in chips ( that,s benefits users easily removed
and selectd any image ).
4.The benefits are that users can easily identify which fields are required and which are optional.

Enhancement:While creating prompt,entry,advertisement mandatory field should be mentioned.

---

src/components/Profile/SettingsTab.vue
src/stores/__tests__/visitor.spec.js
src/stores/prompts.js
src/stores/user.js
src/stores/visitors.js

fix:#544 fixed failing vitest tests

---

firestore.indexs.json
src/stores/comments.js

comments-sorting-fixed

---

src/components/Admin/ManagePromptsEntries.vue

Improvement/manage prompts & entries filter data 546

---

src/layouts/MainMenu.vue

fixes #569 default prompt and entries instead of ads

---

src/components/Admin/EntryCard.vue

fix:#567 fix for entry not editable

---

src/components/Profile/ProfileTab.vue

Fixed: remove-prefix-val-for-social-network-field

Fixed: remove-prefix-val-for-social-network-field

---

src/components/Profile/ProfileTab.vue
src/components/Profile/Web3ModalComponent.vue
src/stores/wallet.js

Now, we can  add, update and delete the crypto wallet address.

Enhancement:save crypto wallet address 533

---

src/components/Posts/ThePost.vue
src/stores/likes.js

Improved immediate ui feedback for likes and dislikes so at the moment of liking or disliking icons would change immediately. Also buttons won't have effect when request is in process.  
https://github.com/user-attachments/assets/1da80c4a-b9e7-4b64-983e-ca6588db2a6c

feat:#502 Improved immediate ui feedback for likes and dislikes

---

src/components/Profile/ProfileTab.vue

profile picture field improved

profile picture field improved

---

src/components/Advertiser/AdvertiseCard.vue

fix #589 
Changed the minimum amount for creating advertisement from 0.0001 to 3 usd.

feat:#589 - set minimum budget for ad to 3 usd

---

index.html

Fixes #597 .
Removed google tag manager and tracking
--

fix:#597 - removed google tag manager and tracking

---

src/components/Advertiser/AdvertiseCard.vue
src/components/Advertiser/AdvertiserTable.vue
src/web3/adCampaignManager.js

Quick fix for not creating ads. Fix for not updating total ad cost. Changed matic to POL naming

fix:#601 - fix error for creating ads. Ads cost not updating fix

---

src/stores/advertises.js

Fixes #586 .
Reduced unnecessary steps of an admin to approve new ad. 
Easy fix that doesn't require a lot of changes to revert changes and let admin approve new ads.
This change allows users to create an ad that will be automatically published after a successfull creation.

feat:#586 - Removed unnecessary ad validation

---

src/components/Posts/TheComments.vue

- fixed duplicate comment if hitting enter multiple times.
- fixed Comment Creation with Only Spaces or Empty Input Should be Restricted

fix:#575, #600 - duplicate comment if hitting enter multiple times & Restricted Only Spaces or Empty

---

src/components/Posts/TheComments.vue

Fixed first comment loading issue.

fix:#574 - First comment loading issue

---

index.html
src/components/Admin/ManageFeedbacks.vue
src/components/Profile/LoginForm.vue
src/layouts/MainMenu.vue
src/stores/feedbacks.js

Fixes #618 
implemented feedback tab loader
--

fix:#618 - implemented feedback tab loader

---

src/stores/user.js

fix:#623 - sign-in-error

---

src/components/Admin/FundDepositCard.vue
src/components/Admin/WalletPaymentCard.vue
src/components/Advertiser/AdvertiseCard.vue
src/web3/adCampaignManager.js
src/web3/transfers.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

changes concerned strings

---

src/components/Advertiser/AdvertiserTable.vue

Fixes # (issue)
- update  advertise cost calculation.

fix:#627 - Update cost calculation

---

src/components/Admin/CryptoTransactionDetailCard.vue
src/components/Admin/EntryCard.vue
src/components/Admin/FundDepositCard.vue
src/components/Admin/ManagePromptsEntries.vue
src/components/Admin/PromptCard.vue
src/components/Admin/TableEntry.vue
src/components/Admin/WalletPaymentCard.vue
src/components/Advertiser/AdvertiserTable.vue
src/stores/crypto-transactions.js
src/stores/entries.js

After our Thursday Team Meeting we found some small bugs that have to be fixed before releasing into production. This PR cover one part of those issues, such as:
- Notifications first letter capitalize
- Changed icons logic (when claiming payment the icons should be changed inside admin panel)
- Updating treated entry reactivly after the transaction was successful in order to change the icon
- Updated icons colors
- Fixed some notifications
- Increased entry and prompt description input field for better UX
Fixes # (issue)
#628 
Bug fixes after testing

fix:#628 - Notifications - capitalize first letter + fix grammatical issues

---

src/components/Admin/ManageReports.vue
src/stores/reports.js

Fixes #625 
implemented report tab loader
--

fix:#625 - implemented report tab loader

---

src/components/Profile/LoginForm.vue

The system should not allow only spaces in the Name field.
Fixes #669 

fix:#669 - fixed empty spaces name field

---

src/components/Admin/EntryCard.vue

Entries created using the "Capture Image with Camera", the entry is editable.
Fixes #676 

fix:#676 - non-editable camera capture entry

---

src/components/Admin/ManageUsers.vue
src/stores/user.js

This PR introduces the functionality for admins to delete users individually or in bulk. The implementation includes UI,logic, and validations to ensure smooth operation and secure handling of user deletions.
**Single User Deletion:**
- Added a "Delete" button for each user in the user management table.
- A confirmation prompt is displayed before deletion.
- Upon confirmation, the user is deleted, and the table refreshes to reflect changes.
**Multiple User Deletion:**
- Checkboxes added for each user to enable selection.
- A "Select All" checkbox allows admins to select all users in the current view.
- A "Delete Selected" button triggers bulk deletion after confirmation.
- All selected users are deleted in a single operation, and the UI updates accordingly.
**Admin User Protection:**
- …

feat:#676 - admin can delete single & multiple users

---

package-lock.json
package.json
quasar.config.js
src/boot/clarity.js

Added microsft clarity. 
Contains information about user interactions on the site. Used for analytics and playback of interactions. Clarity collects the following type of events.
Interaction events: click, scroll, mouse move, window resize, selection, input, and so on.
Diagnostic events: script and image errors, logs, performance events, and so on.
Page events: document sizes, page visibility, page unload, metrics, and dimensions about the page.
Custom events: Custom variables/events set by the website based on some event.
Fixes #694 

feat:#694 - added microsoft clarity

---

src/components/Profile/ProfileTab.vue
src/pages/PublicProfilePage.vue
test/cypress/e2e/user-profile.cy.js

The issue arises from improper concatenation of the social media URL with the user's profile data, resulting in an incorrect double URL format.
Fixes #696 
- Prefix Handling:
Added a prefix value for every social media base URL. Users can now input only the part after the base URL, ensuring clean and consistent storage.
- Automatic Removal of Prefix:
If users paste a complete URL (e.g., `https://www.facebook.com/test`), the prefix (`https://www.facebook.com/`) is automatically removed, leaving only the unique identifier (e.g., test).
- Base URL Updates:
Updated the handling of social media base URLs to ensure compatibility and accuracy.
- Code Refactoring:
Reduced code complexity in `profileTab.vue` by implementing more efficient logic for the social media network portion.
----

Fix for Incorrect Social Media URL Redirection (Double URL Issue)

---

.firebaserc
functions/index.js
functions/package-lock.json
functions/package.json
src/components/Admin/ManageUsers.vue
src/stores/user.js
test/cypress/e2e/login-logout.cy.js

This PR addresses an issue where deleting a user from Firestore did not remove their authentication credentials from Firebase Authentication. As a result, users could still log in even after their Firestore data was deleted, causing inconsistencies.
and new test case add
Fixes #683 

fix: #683 - Delete user from Firebase Auth and Firestore, add new test case for user deletion
